### ISSUE TITLE
テーブル設計

### ISSUE THREAD

**Issue by tsubasa1122** [tsubasa1122/twitter-app#1]
今回実装するTwitter風SNSアプリケーションのER図を以下の通り作成した。
今回はIE記法を用いています。
![スクリーンショット 2019-12-16 14 18 51](https://user-images.githubusercontent.com/47236483/70881164-14930880-200f-11ea-8431-29e0a67c1c86.png)

**Comment by tsubasa1122** [comment]
Users : UserProfiles = 1 : 1
Users : Tweets = 1 : 多
Users : Favorites : Tweets = 多 : 1 : 多 (Favoritesテーブルが中間テーブル)
Follow(Users) : Relationships : Follower(Users) = 多 : 1 : 多(Relationshipsテーブルが中間テーブルで、Relationshipsテーブルを通して、ユーザー同士のリレーションを表現しています。

**Comment by daijiromaeyama** [comment]
ER図とアソシエーションを送っていただきありがとうございます。大方は良さそうですね！
1点だけ気になった箇所を以下に記載しますね。

user_profilesテーブルの`user_id`はintと記載されていますが、これはRailsでいうintegerのことでしょうか。今回作成するアプリケーションでユーザー数が膨大になることはないと思いますが、Rails5.1からidカラムはデフォルトで`bigint` になっていることを踏まえて、`bigint`にした方がいいかなと思いました。他のテーブルのidがつくカラムもご確認お願いします。

**Comment by tsubasa1122** [comment]
ご確認ありがとうございますー！！
確かにidはintではなく、bigintの方が良さそうですね！
![スクリーンショット 2019-12-16 21 36 32](https://user-images.githubusercontent.com/47236483/70907492-58f0c980-204c-11ea-80d1-974e1b0797ad.png)
bigintに修正しましたので、お手隙の際に確認お願い致しますー！

**Comment by daijiromaeyama** [comment]
確認しました！
LGTMです！！
次のIssueに行きましょうー！
